server {
    listen 80;
    server_name taska-app.duckdns.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name taskad.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/taskad.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/taskad.duckdns.org/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /llm/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}